# Generated by Django 3.2.3 on 2022-02-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('no', 'product')},
        ),
    ]
